import { JetBrains_Mono} from "next/font/google";
import "./globals.css";
//compinents
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const jetBrainsMono = JetBrains_Mono({
  subsets : ["latin"],
  weight:["100","200","300","400","500","600","700","800"],
  variable :'--font-jetbrainsMono'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} antialiased`}
      >
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
